class Exceptions:
    class FatalError(Exception):
        pass